<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LibraryDomain\LibraryDomain.csproj" />
    <ProjectReference Include="..\LibraryInfraData\LibraryInfraData.csproj" />
    <ProjectReference Include="..\LibraryApplication\LibraryApplication.csproj" />

  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
